# Generated by Django 5.1.1 on 2025-04-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availabletime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availabletime',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
